config/routes.rb
Rails.application.routes.draw do
  scope "/api" do
    post '/user_token' => 'user_token#create'
  end

  get '/profile' => 'users#show'
  resources :users, except: [:show]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'
  resources :appointments
  # resources :users
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
  has_many :notes
  belongs_to :user, optional:true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :appointment, optional:true
  has_one :users, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appointments
  has_many :notes, through: :appointments
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  include Knock::Authenticable
  helper_method :login!, :logged_in?, :current_user, :authorized_user?, :logout!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  # before_action :authenticate_user
  # before_action :set_appointment, only: [:show, :update, :destroy]
  def new
    @appointment = Appointment.new
  end
  def show
    @appointment = Appointment.find params[:id]
  end
  def create
    @appointment = Appointment.create(appointment_params)
  end

  def edit
    @appointment = Appointment.find params[:id]
  end

  def index
     @appointment = Appointment.all
     # render json: @appointment
     # @appointment = current_user.appointments
  end

  def destroy
    appointmentDelete = Appointment.find params[:id]
    appointmentDelete.destroy
    redirect_to appointments_path
  end

  def update
    appointment = Appointment.find params[:id]
    appointment.update appointment_params
    redirect_to(appointments_path)
  end
  private
    def appointment_params
        params.require(:appointment).permit(:time, :date, :title, :description, :address, :timeTo, :aside, :asideTo, :latitude, :longitude, :user_id)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
    @note = Note.new
    render json: @note
  end

  def create

    Note.create note_params
    redirect_to notes_path
  end

  def index
    @notes = Note.all
    render json: @notes
  end

  def show
    @note = Note.find params[:id]
    render json: @note
  end

  def edit
    @note = Note.find params[:id]
  end

  def update
    note = Note.find params[:id]
    note.update(note_params)
    redirect_to note_path(note.id)
  end

  def destroy
    Note.destroy params[:id]
    redirect_to notes_path
  end

  private
  def note_params

    params.require(:note).permit(:message, :user_id, :appointment_id)

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create

    # See if the email address entered actually exists in the 'users' table
    # user = User.find_by email: params[:email]
    #
    # # Did we find a user, and if we did, is the password correct?
    # if user.present? && user.authenticate( params[:password] )
    #   # successful login
    #
    #   # Get Rails to create a new key in a special system variable
    #   # called 'session'; this variable is remembered ACROSS REQUESTS!
    #   # (This persistent memory across requests is implemented using
    #   #  browser cookies, which are stored on your harddrives)
    #   session[:user_id] = user.id
    #
    #   redirect_to user_path(user.id)  # go to show page (/users/10 or whatever)
    #
    # else
    #   # failed login (wrong credentials)
    #
    #   flash[:error] = 'Invalid email or password'
    #   redirect_to login_path  # show the form again
    # end

  render json: {status: "it's working"}
  end # create


  def destroy
    session[:user_id] = nil  # This logs out the user
    redirect_to login_path
  end
end

app/controllers/user_token_controller.rb
class UserTokenController < Knock::AuthTokenController
  skip_before_action :verify_authenticity_token
  def auth_params
    params.require(:auth).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, except: [:new, :create]
  # before_action :set_appointment, only: [:show, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @users = User.
    render :json => @users
  end
  # GET /users/1
  # GET /users/1.json
  def show
    # @user = current_user #User.find params[:id]
    render json: current_user, include: :appointments
  end
  # GET /users/new
  def new
    @user = User.new
  end
  # GET /users/1/edit
  def edit
  end
  # POST /users
  # POST /users.json
  def create
    p 'working from react'
    @user = User.create(user_params)
    if @user.persisted?
      # format.html { redirect_to @user, notice: 'User was successfully created.' }
      render json: {:user_id => @user.id}
    else
      # format.html { render :new }
      render json: {errors: @user.errors.full_messages }, status: 422
    end
  end
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/_form.html.erb
  <%= form_for @appointment do |f| %>
    <div><%= f.label "title: " %><%= f.text_field :title %></div><br>
    <div><%= f.label "description: " %><%= f.text_field :description %></div><br>
    <div><%= f.label "date: " %><%= f.date_field :date %></div><br>
    <div><%= f.label "time: " %><%= f.time_field :time %></div><br>
    <br>
    <div><%= f.submit%><br>
  <% end %>

app/views/appointments/edit.html.erb
<%= render "appointments/form" %>

app/views/appointments/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <% @appointment.each do |x| %>
    <%= x.title %><br>
    <%= x.description %><br>
    <%= x.date %><br>
    <%= x.time.to_s.slice(11..18) %>
    <%= link_to "Edit", edit_appointment_path(x.id) %>
    <%= link_to "Delete", appointment_path(x.id), method:"delete" %><br><br>
  <% end %>
  <%= link_to "Create new appointment", new_appointment_path %>
</body>
</html>

app/views/appointments/new.html.erb
<%= render "appointments/form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalendarProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note do |form| %>
  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="field">
    <%= form.label :appointment %>
    <select name="note[appointment_id]">
      <% Appointment.all.each do |appointment| %>
        <option value="<%= appointment.id %>"><%= appointment.title %></option>
      <% end %>

    </select>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/notes/edit.html.erb
<h1>Notes#edit</h1>
<%= render 'form', link: @note %>

app/views/notes/index.html.erb
<h1>Notes#index</h1>
<% @notes.each do |note| %>
  <%= link_to note.message, note_path(note.id)  %><br>
<% end %><br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>Notes#new</h1>
<%= render 'form', link: @note %>

app/views/notes/show.html.erb
<h1>Notes#show</h1>
<p>
  <strong>Messages:</strong>
  <%= @note.message %>
</p>

<p>
  <strong>Appointment:</strong>
  <%= @note.appointment.title %>
</p>



<%= link_to 'Edit', edit_note_path(@note.id) %> |
<%= link_to 'Delete', note_path(@note.id), method: :delete %> |
<%= link_to 'Back', notes_path %>

app/views/notes/update.html.erb
<h1>Notes#update</h1>
<p>Find me in app/views/notes/update.html.erb</p>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>

<!-- could also just use @user.errors.full_messages here -->
<% if @user.errors.any? %>
    <p>Please correct the following errors:</p>
     <ul>
        <% @user.errors.full_messages.each do |e| %>
          <li><%= e %></li>
        <% end %>
    </ul>
<% end %>

  <%= form_for @user do |f| %>
  <div class="field">
    <div>
    <%= f.label :name %>
    </div>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <div>
    <%= f.label :email %>
    </div>
    <%= f.email_field :email %>

  </div>

  <div class="field">
    <div>
    <%= f.label :password %>
      </div>
    <%= f.password_field :password %>

  </div>
  <div class="field">
    <div>
    <%= f.label :password_confirmation %>
    </div>
    <%= f.password_field :password_confirmation %>

  </div>
  <div class="submit">
  <%= f.submit 'Update' %>
  </div>
<% end %>























</div>
</div>

<br>

app/views/users/index.html.erb
<h2>All Users</h2>


 <% @users.each do |user| %>

 <%= user.name %>

<% end %>

app/views/users/new.html.erb
<div class="main_content">
  <div id="login">


<h2>Create a New Account</h2>
<br>
<!-- could also just use @user.errors.full_messages here -->
<% if @user.errors.any? %>
    <p>Please correct the following errors:</p>
     <ul>
        <% @user.errors.full_messages.each do |e| %>
          <li><%= e %></li>
        <% end %>
    </ul>
<% end %>

  <%= form_for @user do |f| %>
  <div class="field">
    <div>
    <%= f.label :name %>
    </div>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <div>
    <%= f.label :email %>
    </div>
    <%= f.email_field :email %>

  </div>

  <div class="field">
    <div>
    <%= f.label :password %>
      </div>
    <%= f.password_field :password %>

  </div>
  <div class="field">
    <div>
    <%= f.label :password_confirmation %>
    </div>
    <%= f.password_field :password_confirmation %>

  </div>
  <div class="submit">
  <%= f.submit 'Sign up' %>
  </div>


</div>

</div>


<br>





<% end %>

app/views/users/show.html.erb
<div id="profile_page">
<h2>Profile<%# @user.name %></h2>
</div>
<div id="edit_profile">
<h4><%= link_to "Edit Profile", edit_user_path %></h4>
</div>


 <% if @user.image.present? %>
  <%= image_tag @user.image, alt: @user.name, class: 'cocktail' %>
 <% end %>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>